### ISSUE TITLE
Ошибка с рисунками

### ISSUE THREAD

**Issue by KorobetskayaAA** [MayorovaValeria/ORMP#1]
Пути к файлам должны быть относительными, иначе они не будут работать на другом окмпьютере, в другой папке. Т.е. не Source="G:\Осн. разраб. моб. прил\Tiles\Tiles.MayorovaVA\Tiles.MayorovaVA\res\Icon1.png", а Source="res\Icon1.png"

И папка res со всеми иконками должна быть частью проекта. У каждого файла рисунка в свойствах выставить: 
![изображение](https://user-images.githubusercontent.com/22618142/80113753-c3ce8600-8593-11ea-821d-d32d2e86979b.png)

Иначе получается так:
![изображение](https://user-images.githubusercontent.com/22618142/80113527-7c47fa00-8593-11ea-988f-15bbf8ef9461.png)

**Comment by MayorovaValeria** [comment]
Он пишет ошибку, но я ее найти не могу 
![image](https://user-images.githubusercontent.com/62285970/80128928-6e9c6f80-85a7-11ea-8704-491bbf75d70e.png)

**Comment by KorobetskayaAA** [comment]
Пересоберите решение через меню "Сборка". XAML от C# отвалился, такое бывает. Либо какая-то опечатка в имени namespace появилась, что они друг друга перестали видеть

**Comment by KorobetskayaAA** [comment]
Еще возможно, что помимо рисунков, вы изменили настройку "Действие при сборке" и для самого файла xaml. Там должно стоять Page (Страница)

**Comment by MayorovaValeria** [comment]
Вторая версия оказалась правильной. Я так и не смогла найти свойства файла рисунка, все что мне удалось обнаружить, это вот это
![image](https://user-images.githubusercontent.com/62285970/80131795-d3f25f80-85ab-11ea-82c0-e56c280fd434.png)

**Comment by MayorovaValeria** [comment]
Я посмотрела решение проблемы, которые вы предлагали ребятам на прошлых парах и поняла, что у меня даже такого пути "%ваш проект%\bin\Debug\netcoreapp3.1\res\" нет для того, чтобы сделать папку res частью проекта. В общем, я не знаю, может есть другие варианты?
![image](https://user-images.githubusercontent.com/62285970/80143502-f9886480-85bd-11ea-8ca3-93f57f4b16b4.png)
![image](https://user-images.githubusercontent.com/62285970/80143572-12911580-85be-11ea-8432-d8e41965e338.png)

**Comment by KorobetskayaAA** [comment]
Что я вижу из ваших скриншотов.

1. Как я напоминала на последней лекции, у нас есть .NET Framework (старый) и .NET Core (новый). И с тем, и с другим можно создавать WPF. У вас .NET Framework, поэтому exe-файл находится прямо в bin\debug, а папка "netcoreapp3.1" отсутствует. В следующий раз желательно создавать WPF .NET Core, хотя для наших простых задач это не принципиально.
1. Относительный путь задается относительно exe-файла. Где бы он ни находился, к нему и надо складывать папку res, чтобы рисунки отображались при запуске программы.
1. А чтобы рисунки были, когда вы работаете в Visual Studio, надо их добавить и в сам проект. Т.е. у вас в Visual Studio в Обозревателе решений, там же где и файлы App.xaml и MainWindow.xaml должна быть папка "res\" с картинками. Создать ее можно прямо в Обозревателе (ПКМ по проекту -- Добавить).
1. Вот когда файлы есть в Обозревателе решений, вы можете их там выделить и в Свойствах появятся настройки этого файла (как на вашем последнем скриншоте). А когда вы выделяете что-нибудь на форме, то в Свойствах показываются настройки этого элемента (как на предыдущем скриншоте).

**Comment by MayorovaValeria** [comment]
Когда создавала проект очень долго сомневалась в выборе между .NET Framework и .NET Core. Надо было сразу у вас спросить. Буду иметь  в виду. Я сложила папку res туда где лежит exe-файл, а на этапе добавления папки в Visual Studio у меня возникли проблемы, я смогла добавить только сами картинки, а как я понимаю нужно именно папку. Когда я пытаюсь добавить ее как существующий элемент, он добавляет только картинки. А если я выбираю создать новую папку(что мне кажется не правильно), получаю на выходе вот это
![image](https://user-images.githubusercontent.com/62285970/80182646-67617a00-8618-11ea-8747-1b61326124ba.png)

**Comment by KorobetskayaAA** [comment]
Потому что эта папка у вас уже есть, она только не включена в проект. Сделайте, как здесь показано: https://fooobar.com/questions/12499/how-do-i-add-an-existing-directory-tree-to-a-project-in-visual-studio

**Comment by MayorovaValeria** [comment]
Сделала, все равно при запуске картинки не отображаются
![image](https://user-images.githubusercontent.com/62285970/80187824-5e28db00-8621-11ea-9748-a828316a9e71.png)

**Comment by KorobetskayaAA** [comment]
В папке bin\Debug есть папка res с картинками?

Можно еще попробовать путь в XAML записать с прямой косой чертой "res/Icon1.png"

**Comment by KorobetskayaAA** [comment]
Так, подождите, невнимательно скриншот ваш посмотрела. Еще раз. Папка res должна быть в двух местах: прямо в вашем проете и в bin\Debug. А вы добавили в ваш проект весь путь bin\Debug\res. Там должна быть вторая копия папки, а в проекте - просто папка res.

**Comment by KorobetskayaAA** [comment]
И поставьте рисункам не только свойство "Действие при сборке", но и "Копировать в выходной каталог". Тогда в bin\Debug они автоматически будут добавляться.

**Comment by MayorovaValeria** [comment]
А bin мне удалить получается?

**Comment by MayorovaValeria** [comment]
Точнее исключить из проекта и добавить папку res которая здесь находится
![image](https://user-images.githubusercontent.com/62285970/80188559-6897a480-8622-11ea-8219-3fd62dc107b3.png)

**Comment by KorobetskayaAA** [comment]
Да, исключить bin и добавить res по прямому пути.

**Comment by MayorovaValeria** [comment]
Ура, спасибо, получилось!) Сейчас обновлю репозиторий
